name: Docker Image CI

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Login to Github Package Registry
      run: docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{secrets.REGISTRY_TOKEN}}
    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
    - name: Build the tagged Docker image
      run: docker build ./circleci/node -t docker.pkg.github.com/${{github.repository}}/ci-node-aws:${{steps.vars.outputs.tag}}
    - name: Push the tagged Docker image
      run: docker push docker.pkg.github.com/${{github.repository}}/ci-node-aws:${{steps.vars.outputs.tag}}
    - name: Build the latest Docker image
      run: docker build ./circleci/node -t docker.pkg.github.com/${{github.repository}}/ci-node-aws:latest
    - name: Push the latest Docker image
      run: docker push docker.pkg.github.com/${{github.repository}}/ci-node-aws:latest
